# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20170224_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensephoto',
            name='claim',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpenseClaim'),
            preserve_default=False,
        ),
    ]
