# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20170224_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensephoto',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='expenses.ExpenseClaim'),
        ),
    ]
